#!/usr/bin/env python
# Autogenerated file (by doconce sphinx_dir)
# Purpose: create HTML Sphinx version of report

import glob, sys, os, commands, shutil

sphinx_rootdir = 'sphinx-rootdir'

def system(cmd, capture_output=False, echo=True):
    if echo:
        print 'running', cmd
    if capture_output:
        failure, outtext = commands.getstatusoutput(cmd)
    else:
        failure = os.system(cmd)
    if failure:
        print 'Could not run', cmd
        sys.exit(1)
    if capture_output:
        return outtext

# Filter doconce format to sphinx format and copy to sphinx directory
files = ['report']
print """

"""
for file in files:
    system('doconce format sphinx %s' % file)
    system('doconce sphinxfix_localURLs %s.rst' % file)

    enc = system('doconce guess_encoding %s.rst' % file, capture_output=True)
    if enc == "iso-8859-1":
        # sphinx does not like non-English characters in iso-8859-1
        system('doconce change_encoding iso-8859-1 utf-8 %s.rst' % file)

    shutil.copy('%s.rst' % file, sphinx_rootdir)

# Copy figures
figdirs = glob.glob('figs*')
for figdir in figdirs:
    destdir = os.path.join(sphinx_rootdir, figdir)
    if os.path.isdir(figdir) and not os.path.isdir(destdir):
        print 'copying', figdir, 'to', sphinx_rootdir
        shutil.copytree(figdir, destdir)

# Copy linked local files, placed in _static*, to sphinx-rootdir/_static
staticdirs = glob.glob('_static*')
for staticdir in staticdirs:
    # Copy files whose linkes were fixed by doconce sphinxfix_localURLs
    # or files stored explicitly in staticdir by the user
    system('cp -r %s/* sphinx-rootdir/_static/' % staticdir)
    # (Note: must do cp -r since shutil.copy/copytree cannot copy a la cp -r)

# Note that HTML files in staticdirs may contain links to local HTML
# files that must also be copied (sphinxfix_localURLs can only detect
# the first link).

# Compile web version of the sphinx document
os.chdir(sphinx_rootdir)
print os.getcwd()
system('make clean')
system('make html')
print """
google-chrome sphinx-rootdir/_build/html/index.html
"""
